### ISSUE TITLE
PPD version problems

### ISSUE THREAD

**Issue by jjames55** [chuckcharlie/docker-cups-airprint-brother#39]
After last update, it stops printing with:

"The PPD version (5.3.4) is not compatible with Gutenprint 5.3.5. Please run `/usr/sbin/cups-genppdupdate' as administrator."

That script can't really run in my container for some reason. Driver is for HP 3525X Laserjet printer btw.

regards,
Jesper

**Comment by chuckcharlie** [comment]
You can run it locally on your host if you’d like. Just copy the new one back once updated. I’ll fix the script in the container when I have a moment. Copy script out. docker cp cups:/usr/sbin/cups-genppdupdate .Fix the shebang. sed -i '1s|.*|#!/usr/bin/perl -w|' cups-genppdupdateRun it. perl ./cups-genppdupdateOn May 7, 2025, at 3:31 AM, jjames55 ***@***.***> wrote:﻿
jjames55 created an issue (chuckcharlie/cups-avahi-airprint#39)
After last update, it stops printing with:
"The PPD version (5.3.4) is not compatible with Gutenprint 5.3.5. Please run `/usr/sbin/cups-genppdupdate' as administrator."
That script can't really run in my container for some reason. Driver is for HP 3525X Laserjet printer btw.
regards,
Jesper

**Comment by krohrbaugh** [comment]
Same issue here, in both `1.2.0` and `1.2.1`.

I pinned my image back at `1.1.5` and everything is working again.

**Comment by chuckcharlie** [comment]
Could either of you provide a ppd file that I can test with? @krohrbaugh @jjames55

**Comment by jjames55** [comment]
I also had to downgrade to 1.1.5 to get some prints out. Are the ppd files not in the image?

If not, which file do you need?

**Comment by chuckcharlie** [comment]
No, the PPD files are not in the image. They are generated from gutenprint or you provide your own. In the container they will be in `/config/ppd/`. You can view them on your host in the config directory you have bound to the container.
I just updated the container now. Try pulling the latest image, then run:
```
docker exec <your container name> sh -c 'for ppd in /config/ppd/*.ppd; do perl /usr/sbin/cups-genppdupdate -v "$ppd"; done'
```
Then restart the container and see if that fixed your issue.

**Comment by krohrbaugh** [comment]
I've attached the `ppd` files that only worked up to the `1.1.5` release: [ppd.zip](https://github.com/user-attachments/files/20427401/ppd.zip)

I then pulled the `1.2.1` release once again, and confirmed that it still failed with:

> The PPD version (5.3.4) is not compatible with Gutenprint 5.3.5.

Then, I ran the `docker exec` command @chuckcharlie provided, and got the following output:

```
Updating PPD files from Gutenprint 5.3.5
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultColorModel (Gray)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultDuplex (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultInputSlot (Standard)
/config/ppd/HL1440_Basement.ppd: Set *DefaultPageRegion to A4
/config/ppd/HL1440_Basement.ppd: Set *DefaultPageSize to A4
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultResolution (301x300dpi)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpBrightness (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpColorCorrection (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpColorPrecision (Normal)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpContrast (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpDensity (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpDitherAlgorithm (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpFineBrightness (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpFineContrast (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpFineDensity (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpFineGamma (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpGamma (None)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpImageType (TextGraphics)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpLinearContrast (False)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpQuality (Standard)
/config/ppd/HL1440_Basement.ppd: Preserve *DefaultStpiShrinkOutput (Shrink)
Updated /config/ppd/HL1440_Basement.ppd using gutenprint.5.3://brother-hl-1440/expert
Updated 1 PPD file.  Restart cupsd for the changes to take effect.
Updating PPD files from Gutenprint 5.3.5
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultColorModel (Gray)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultDuplex (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultInputSlot (Standard)
/config/ppd/HL1440_Upstairs.ppd: Set *DefaultPageRegion to A4
/config/ppd/HL1440_Upstairs.ppd: Set *DefaultPageSize to A4
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultResolution (301x300dpi)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpBrightness (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpColorCorrection (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpColorPrecision (Normal)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpContrast (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpDensity (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpDitherAlgorithm (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpFineBrightness (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpFineContrast (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpFineDensity (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpFineGamma (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpGamma (None)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpImageType (TextGraphics)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpLinearContrast (False)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpQuality (Standard)
/config/ppd/HL1440_Upstairs.ppd: Preserve *DefaultStpiShrinkOutput (Shrink)
Updated /config/ppd/HL1440_Upstairs.ppd using gutenprint.5.3://brother-hl-1440/expert
Updated 1 PPD file.  Restart cupsd for the changes to take effect.
```

Following this, I restarted the container, and was able to print from the `1.2.1` release. 🥇 

Hopefully this gets you to a spot where you can incorporate the `ppd` upgrade into the container itself. I, sadly, do not know enough about CUPS or Gutenprint to understand where that work should occur.

Thank you!

**Comment by chuckcharlie** [comment]
Yeah @krohrbaugh I wasn't sure if I wanted to have the container automatically update the files or not. So I left it manual for now. I could def include it if it's a widespread issue. I added these steps to the readme.

**Comment by jjames55** [comment]
Ok i just got around to fixing this now. 

When i install a 'latest' container, there's no perl in it anywhere, so i can't to these updates...

**Comment by chuckcharlie** [comment]
This has been fixed. The `cups-genppdupdate` script wasn't running because it's a Perl script and the container was missing the `perl` dependency, plus the script's shebang was incorrect. Both have been fixed.

If you're upgrading from an older version and your existing PPD files (in `/config/ppd`) are from Gutenprint 5.3.4, you can update them by running inside the container:

```
cups-genppdupdate
```

Fresh installs will have the correct 5.3.5 PPDs from the start. Please update to the latest image and let me know if you still have issues.

**Comment by chuckcharlie** [comment]
This should be fixed in v2.0 / `latest`. The container now has `perl` installed and the `cups-genppdupdate` shebang is correct, so running `cups-genppdupdate` inside the container works directly. Going to close this one out, please reopen (or ping me) if you're still hitting it on the latest image!

**Comment by jjames55** [comment]
I don't see a V2.0 and latest uses 1.2.1 where the problems still is?
